### ISSUE TITLE
IMU repeated time stamps

### ISSUE THREAD

**Issue by kzamzam** [CIFASIS/dataset-processing#3]
The IMU has a lot of repeated time stamps, especially in sequences 1,2,3, and 6. Is there a way to solve this issue? Does uniformly distributing the IMU readings over the whole time ( same initial and final timestamps ) make sense? or will it completely ruin the synchronization between images?

**Comment by kzamzam** [comment]
@taihup any ideas?

**Comment by taihup** [comment]
We just fixed this issue in the Rosario dataset, data is already fixed now.
