### ISSUE TITLE
Ground truth GPS data for Sequence 2

### ISSUE THREAD

**Issue by kzamzam** [CIFASIS/dataset-processing#4]
The Z values for the GPS seems to be increasing from zero to around 4.8m, this does not make sense, especially that the path taken includes a 180° turn, which means that if even the field had some elevation it should start decreasing back after the turn.

**Comment by jcremona** [comment]
Dear @kzamzam , we are aware of this problem. There is no elevation on the field, it is a GPS-RTK problem. This issue only appears in sequence 02. Does ignoring Z work for you or do you need higher precision?

**Comment by kzamzam** [comment]
It is fine by me, was just making sure.
