### ISSUE TITLE
S-MSCKF params

### ISSUE THREAD

**Issue by kzamzam** [CIFASIS/dataset-processing#5]
Hi @taihup , I am running the S-MSCKF trying to replicate the results in the paper, I am pretty off, would you tell me which paramters you used?

**Comment by taihup** [comment]
Hi @kzamzam, we just updated the Rosario dataset (fixing some issues) and provided an exhaustive evaluation of different SLAM system (S-MSCKF is included). Please feel free to check it out: https://github.com/CIFASIS/slam_agricultural_evaluation
