### ISSUE TITLE
Did the server fall?

### ISSUE THREAD

**Issue by ghost** [CIFASIS/dataset-processing#8]
Since Wednesday I am not able to download it. I already did some downloads successfully in the past.

**Comment by taihup** [comment]
Hi, I Just checked and the link are working, I am able to download the files. Try from another PC or network, it has already happened that there some firewall in the institution that does not allow to download them.

**Comment by jcremona** [comment]
> Since Wednesday I am not able to download it. I already did some downloads successfully in the past.

Hi @yriuss. Try copying the download link and pasting it in a new tab. I just downloaded it successfully using Google Chrome.

**Comment by ghost** [comment]
It was indeed something specific from my pc or network. Doing what @jcremona said on another pc worked for me. Thank you!
